# configuration for https://travis-ci.org/HashEngineering/dashj
sudo: false
dist: trusty
language: java
addons:
  hosts:
    - host
  hostname: host
jdk: oraclejdk8
install: true # remove default
script:
  - cd bls
  - mvn clean package -Pbuild-bls-only -pl :dashj-bls -DskipTests -Dmaven.javadoc.skip=true --settings ../.travis.settings.xml
  - cd ..
  - mvn -q clean install -Pno-network --settings .travis.settings.xml
  - jdk_switcher use openjdk8
  - cd core
  - mvn -q clean install -Pno-network --settings ../.travis.settings.xml

after_success:
  - cd ../core
  - mvn jacoco:report coveralls:report