# configuration for https://travis-ci.org/HashEngineering/dashj
sudo: false
dist: trusty
language: java
addons:
  hosts:
    - host
  hostname: host
jdk: oraclejdk8
install: true # remove default
script:
  - mvn clean install -Pno-network
  - jdk_switcher use openjdk8
  - cd core
  - mvn clean package -Pno-network

after_success:
  - cd ../core
  - mvn jacoco:report coveralls:report